<expr>  ::=  <term> {( "+" | "-" ) <term> }
<term>  ::=  <pow> <term1>
<term1> ::=  <pow>  {( "*" | "/" ) <pow>  }
<pow>   ::=  <fact> "^" <pow>
         |   <fact>
         |   "-" <pow>
<fact>  ::=  number
         |   func_id "(" <expr> ")"
         |   "(" <expr> ")"
         |   x