<expr>  ::=  <term> <expr1>
<expr1> ::=  "+" <term> <expr1>
         |   "-" <term> <expr1>
         |   empty
<term>  ::=  <pow> <term1>
<term1> ::=  "*" <pow> <term1>
         |   "/" <pow> <term1>
         |   empty
<pow>   ::=  <fact> "^" <pow>
         |   <fact>
         |   "-" <pow>
<fact>  ::=  number
         |   func_id "(" <expr> ")"
         |   "(" <expr> ")"
         |   x